spring:
    application:
        name: volley-backend
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username:  ${DB_USERNAME}
    jpa:
        hibernate:
            ddl-auto: none #update
        properties:
            hibernate:
               ## dialect: org.hibernate.dialect.PostgreSQL82Dialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    output:
        ansi:
            enabled: 'ALWAYS'


