spring:
    application:
        name: volley-backend
    server:
        port: 8080
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connectionTimeout: 1000 #20000
            maximumPoolSize: 2 #5
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username:  ${DB_USERNAME}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none #update
        properties:
            hibernate:
                format_sql: true
                #jdbc:
                 #   lob:
                 #       non_contextual_creation: true
    output:
        ansi:
            enabled: 'ALWAYS'


